name: publish

on:
  push:
    branches:
    - main

jobs:
  build-n-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
    - uses: chrislennon/action-aws-cli@v1.1
      with:
        node-version: '16'
    - run: npm install --save react react-dom
    - run: npm run build
    - run: aws sts get-caller-identity
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    